{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "quilla.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "quilla.name" . }}
    helm.sh/chart: {{ include "quilla.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
{{- end }}
